### ISSUE TITLE
Some pins are inaccesible by pinNumber

### ISSUE THREAD

**Issue by ivantodorovich** [nebrius/raspi-gpio#2]
``` js
var ledGreen  = new gpio.DigitalOutput('P1-11')    // this works!
var ledGreen  = new gpio.DigitalOutput(17)         // this works!

var ledGreen  = new gpio.DigitalOutput('P1-13')    // this works!
var ledGreen  = new gpio.DigitalOutput(27)         // this doesnt X_X
```

``` js
ledGreen.write(gpio.HIGH)
```

It doesn't throw any errors, but the led doesn't turn on using pinNumber 27

I've notices some pins work, others don't... that's unusual. Any ideas why?

PD: testing on `Raspberry Pi B+`

**Comment by ivantodorovich** [comment]
After looking at the code, I've noticed the issue should actually belong to `raspi-board`, since that's the module responsible for resolving pin numbers.

I've noticed that `board.getPinNumber(17)` actually returns `null`. I don't know why, but somehow it translates to `GPIO17` :fearful:  

I guess it accidentaly works because `board.getPinNumber('P1-11')` returns `0` and `!0 == !null` ¿? Didn't really look at the code that hard.

`board.getPinNumber('P1-13')` returns `2`, and `board.getPinNumber(27)` returns `27`

It seems that `gpio.DigitalOutput ( Number )` expects a pin number as described by `raspi-board`'s mappings. It doesn't really reflect the raspberry pinout !

http://www.jameco.com/Jameco/workshop/circuitnotes/raspberry_pi_circuit_note_fig2a.jpg

Is this expected???

**Comment by ivantodorovich** [comment]
Ok,

After reading `raspi-board`'s README, I now understand that `gpio.DigitalOutput ( Number )` expects a Wiring Pi pin number !

That's really confusing! `raspi-gpio` README didn't say anything about this.

In any case, I don't think this is expected to work:

``` js
var ledRed = new gpio.DigitalOutput('asdasdasd') // 'asdasdasd' --> null --> 0 --> 'P1-11'
ledRed.write(gpio.HIGH) // turn on 'P1-11'
```

**Comment by nebrius** [comment]
I haven't had time to go through everything yet, I'm in Berlin for JSConf EU and my time is pretty limited at the moment.

My initial impression is that it sounds like there is a bug with coercing null to 0 somewhere, and that needs to be fixed. However, `gpio.DigitalOutput()` absolutely can take an alias. Take a look at https://github.com/nebrius/raspi-peripheral/blob/master/index.js#L39

I'll try and take a look if I get some free time somewhere, or at the very least when I'm back in the US later this week.

**Comment by nebrius** [comment]
oh, I almost forgot to mention, `getPinNumber(17)` and `getPinNumber(27)` should return null on a B+, since the wiring pi numbers stop at 16.

Hope this helps.

**Comment by nebrius** [comment]
ok, I finally had a chance to sit down and do some testing, just to be sure, and here's what I found.
- If you pass in an invalid pin alias to any peripheral constructor, it fails silently and weird behavior happens. This is a legit bug in raspi-peripheral which I have already fixed, and will hopefully have published sometime tonight or tomorrow (PDT)
- If you call `getPinNumber(17)`, you get null, as expected (there is no Wiring Pi pin 17 on the B+)
- If you call `getPinNumber(27)` on the B+, you get 27, as expected (this will return null on older boards that don't have a wiring pi pin 27).
- If you call `new gpio.DigitalOutput('GPIO27')` on the B+, it resolves to wiring pi pin 2, as expected
- If you call `new gpio.DigitalOutput('asdasdasd')`, you will now get an error with the update to raspi-peripheral

I also added the blurb about pin numbering schemes from the [Raspi IO README](https://github.com/nebrius/raspi-io/blob/master/README.md#pin-naming) to this and a few other READMEs (will push soon, once I sort some other stuff out).

Sorry for the confusion, I hope this helps!

**Comment by ivantodorovich** [comment]
Excellent news, thank you!

El lun., oct. 12, 2015 11:33 PM, Bryan Hughes notifications@github.com
escribió:

> ok, I finally had a chance to sit down and do some testing, just to be
> sure, and here's what I found.
> - If you pass in an invalid pin alias to any peripheral constructor,
>   it fails silently and weird behavior happens. This is a legit bug in
>   raspi-peripheral which I have already fixed, and will hopefully have
>   published sometime tonight or tomorrow (PDT)
> - If you call getPinNumber(17), you get null, as expected (there is no
>   Wiring Pi pin 17 on the B+)
> - If you call getPinNumber(27) on the B+, you get 27, as expected
>   (this will return null on older boards that don't have a wiring pi pin 27).
> - If you call new gpio.DigitalOutput('GPIO27') on the B+, it resolves
>   to wiring pi pin 2, as expected
> - If you call new gpio.DigitalOutput('asdasdasd'), you will now get an
>   error with the update to raspi-peripheral
> 
> I also added the blurb about pin numbering schemes from the Raspi IO
> README
> https://github.com/nebrius/raspi-io/blob/master/README.md#pin-naming to
> this and a few other READMEs (will push soon, once I sort some other stuff
> out).
> 
> Sorry for the confusion, I hope this helps!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nebrius/raspi-gpio/issues/2#issuecomment-147577894.
> 
> ## 

Iván Todorovich

**Comment by nebrius** [comment]
Everything is now published! Thanks again for filing the issue and digging in to it!

**Comment by nebrius** [comment]
Sorry, looks like I forgot to close this issue. Feel free to reopen it if you are still having issues.
