### ISSUE TITLE
BADPLATFORM

### ISSUE THREAD

**Issue by wzr1337** [nebrius/raspi-gpio#8]
Hi,

I get the following error during instal:

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raspi" "raspi-gpio" "--save"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: raspi-gpio@5.0.0
npm ERR! notsup Valid OS:    any
npm ERR! notsup Valid Arch:  arm
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

Environment:

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

node v6.7.0

npm 3.10.3

**Comment by wzr1337** [comment]
My bad.. I was using sshfs from my Mac, not noticing that I was in the wrong terminal :(

**Comment by nebrius** [comment]
I'm glad you figured it out! TBH that's why I added that check there...I had too many times where I tried to install it on the wrong window myself 😄
